### ISSUE TITLE
GridCtrl using MC_LPSTR_TEXTCALLBACK bug

### ISSUE THREAD

**Issue by Bugzero71** [mity/mctrl#44] opened 2016-12-16 11:45 UTC
I'm using mctrl version 0.11.2. With Grid control without OWNERDATA flag, I'm configuring a table with all columns defined except column 1 which needs to be calculated.

An assertion is throw with the next code

```cpp
  MC_TABLECELLW tc;

  // Insert cell [row,0]
  tc.fMask = MC_TCMF_TEXT | MC_TCMF_FLAGS;
  tc.dwFlags = MC_TCF_ALIGNLEFT | MC_TCF_ALIGNVCENTER;
  tc.pszText = const_cast<LPWSTR>(label.getLabelNameW().GetString());
  ::SendMessage(m_hwndMemories, MC_GM_SETCELLW, MAKEWPARAM(0, row), (LPARAM)&tc);

  tc.fMask = MC_TCMF_TEXT | MC_TCMF_PARAM | MC_TCMF_FLAGS;
  tc.dwFlags = MC_TCF_ALIGNCENTER | MC_TCF_ALIGNVCENTER;
  tc.pszText = MC_LPSTR_TEXTCALLBACKW;      // (-1)
  tc.lParam = LABEL2LPARAM(label.getData().uiID);
  ::SendMessage(m_hwndMemories, MC_GM_SETCELLW, MAKEWPARAM(1, row), (LPARAM)&tc); // Exception is thrown
```

The exception is thrown in function:

```cpp
WCHAR*
mc_str_n_W2W(const WCHAR* restrict from_str, int from_len, int* restrict ptr_to_len)
{
    WCHAR* to_str = NULL;
    int to_len = 0;

    if(from_str == NULL)
        goto out;

    if(from_len < 0)
        from_len = wcslen(from_str);               <-------- Exception
    to_len = from_len;

    to_str = (WCHAR*) malloc((to_len + 1) * sizeof(WCHAR));
    if(MC_ERR(to_str == NULL)) {
        MC_TRACE("mc_str_n_W2W: malloc() failed.");
        return NULL;
    }

    memcpy(to_str, from_str, to_len * sizeof(WCHAR));
    to_str[to_len] = L'\0';

out:
    if(ptr_to_len != NULL)
        *ptr_to_len = to_len;
    return to_str;
}
```

MC_GN_GETDISPINFOW message is not thrown.

Before that, I tested control using OWNERDATA and all was fine, but the only data I need to change in control is value in column 1 (4 columns are shown) and I thought it would be faster to do this way.

**Comment by mity** [comment] 2016-12-16 16:15
Reproduced. I will take a look on it.

Thanks for the report.

**Comment by mity** [comment] 2016-12-16 21:25
I have committed a fix. It got only limited testing so far.

**Comment by Bugzero71** [comment] 2016-12-19 08:48
Thank you very much. I'll test it today.

**Comment by Bugzero71** [comment] 2016-12-19 10:25
Hi Martin, I've tested the patch, message MC_GN_GETDISPINFOW is sent and all code seems to work properly, but I have some comments:

1. In MC_GN_GETDISPINFOW documentation (grid.h, line 1035) we can see this text:

```cpp
/*
 * ...
 * When sending the notification, the control sets @c MC_NMGDISPINFO::wColumn
 * and @c MC_NMGDISPINFO::wRow to identify the cell. The control also sets
 * @c MC_NMTLDISPINFO::item::lParam (however if the style @ref MC_GS_OWNERDATA
 * is in effect, it is always set to zero).
 * ...
 */
```
You talk about MC_NMTLDISPINFO, probably is a copy/paste error with tree list control. By the way, lParam is provided correctly.

2. Cell struct in MC_NMGDISPINFO has a fMask value defined as MC_TCMF_TEXT. I see how it works in lines 613 to 627 in grid.c but in line 664 you get the value in dwflags even if MC_TCMF_FLAGS is not specified in fMask. I don't consider this an error, but it could be better this way

```cpp
  if (info.cell.dwFlags & MC_TCMF_FLAGS)
  {
    di->flags = info.cell.dwFlags;
  }
```

3. We have introduced an important error!!!
In table.c, line 38 we can see:

```cpp
    if(cell->text != NULL)
        free(cell->text);               // assertion
```

This should be replaced with

```cpp
    if(cell->text != NULL && cell->text != MC_LPSTR_TEXTCALLBACK)
        free(cell->text);               // assertion
```

I will continue checking the control

**Comment by mity** [comment] 2016-12-19 11:23
1 and 3 are fixed.

2 is imho fully ok as it is: It is an internal function which has to collect **at least** those data calller needs. If it fills more, it is not a problem anywhere. And because assignment of (unsigned) integer is as cheap operation as it is (about as cheap or cheaper then evaluating the condition in the `if` you propose), adding the `if` would be just superfluous.

**Comment by Bugzero71** [comment] 2016-12-19 11:26
Ok. No problem with 2.

**Comment by Bugzero71** [comment] 2016-12-19 11:29
Sorry Martin.
In commit 3b90b7b1c34e1... you have only corrected MC_NMGDISPINFO but not item. In this structure the element is called cell.
I'm affraid

**Comment by mity** [comment] 2016-12-19 11:36
Ouch. That happens when I am hurrying. Better?

**Comment by Bugzero71** [comment] 2016-12-19 11:39
Sorry. This is better but... File grid.h, line 995 you need to change MC_NMGDISPINFO also. This was the multi-byte message.

**Comment by mity** [comment] 2016-12-19 20:38
Done more carefully now. :-)

**Closed by mity** 2016-12-19 20:38 UTC
Labels: bug
